AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - net.mporter::grouch-trash-holiday-schedule-service
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  GrouchTrashHolidayScheduleServiceApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: AWS_IAM

  GrouchTrashHolidayScheduleServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: net.mporter.grouch.holiday.StreamLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: .
      MemorySize: 3008
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref HolidayTable
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            RestApiId: !Ref GrouchTrashHolidayScheduleServiceApi
            Path: /{proxy+}
            Method: any
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -Xverify:none

  HolidayTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Holiday
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S

      KeySchema:
        - AttributeName: name
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  GrouchTrashHolidayScheduleServiceApi:
    Description: URL for application
    Value: !Sub 'https://${GrouchTrashHolidayScheduleServiceApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
    Export:
      Name: GrouchTrashHolidayScheduleServiceApi
