# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Deploy Grouch Trash Holiday Schedule Service

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Build with Maven
      run: ./mvnw clean package

    - name: Sam Build
      run: sam build

    - name: SonarCloud Scan
      run: ./mvnw -Dsonar.login=${SONAR_TOKEN} verify sonar:sonar
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Check Sonar Status
      run: |
        status=$(curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=grouch-trash-holiday-schedule-service)
        echo $status | jq '.'
        status=$(echo $status | jq '.projectStatus.status')
        test '"OK"' = $status